services:
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
    - "8000:8000"
    networks:
      - web
      - data
  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - 80:80
    networks:
      - web

networks:
  web:
  data:
        

volumes:
  postgres:
